# foundry.toml
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
holesky = "${HOLESKY_RPC_URL}"
sepolia_chain = "${SEPOLIA_RPC_URL}"

[etherscan]
holesky = { key = "${ETHERSCAN_API_KEY}" }

[profile.remapping]
"@openzeppelin/contracts/" = "lib/openzeppelin-contracts/contracts/"
"forge-std" = "lib/forge-std/src/"

